### ISSUE TITLE
There seems to be a problem with the class Resample1d in the DS block using the get_output_size function.

### ISSUE THREAD

**Issue by howitry** [f90/Wave-U-Net-Pytorch#4]
In this function,when the transpose is False and padding is reflect,the output_size is equal to the input_size.But in get_input_size function under the same conditions:input_size=(output_size - 1)*self.stride + 1 (stride!=1).I think the output_size should equal to the (input_size-1)/self.stride+1 in the DS block using the get_output_size function.

**Comment by f90** [comment]
@howitry I don't think I fully understand the issue. Which function exactly contains the wrong code? Are you talking about stride=1 or stride > 1 case?

**Comment by howitry** [comment]
The problem exist in the class Reampled1d under the waveunet_utils.py. I think the get_output_size function is the inverse problem of  the get_input_size function under the same conditions.But when the transpose is False and padding is reflect,the output_size is equal to the input_size in the get_output_size function.I think I think the output_size should equal to the (input_size-1)/self.stride+1 in this function.

**Comment by f90** [comment]
Getting rid of these functions in the next version since they make the implementation a lot more complicated :) Thanks for noticing this though!
