### ISSUE TITLE
train problems

### ISSUE THREAD

**Issue by qyyys** [f90/Wave-U-Net-Pytorch#8]
Here's a problem；

RuntimeError: ffmpeg or ffprobe could not be found! Please install them before using stempeg

But I have both libraries installed

could someone help me? thankyou

**Comment by f90** [comment]
Hey, did you check in your terminal whether ffmpeg and ffprobe commands don't return an error? Also check that they are on the sytems PATH so they are accessible from anywhere.

**Comment by YadongChen-1016** [comment]
> Here's a problem；
> 
> RuntimeError: ffmpeg or ffprobe could not be found! Please install them before using stempeg
> 
> But I have both libraries installed
> 
> could someone help me? thankyou

Please refer to this blog, which may help you.     
https://blog.csdn.net/b15040915/article/details/114895645

**Comment by f90** [comment]
Closing this for now since I assume this was solved by installing ffmpeg+ffprobe properly
